name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    uses: platform-mesh/.github/.github/workflows/job-node-test.yml@9ddacafbe3260312cb1cc3f9974ad2fece8effe0
    secrets: inherit # zizmor: ignore[secrets-inherit]

  quality-gate:
    if: always()
    permissions: {}
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check results
        env:
          BUILD_RESULT: ${{ needs.build.result }}
        run: |
          if [[ "${BUILD_RESULT}" != "success" ]]; then
            echo "build failed"
            exit 1
          fi
