name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    uses: platform-mesh/.github/.github/workflows/job-node-test.yml@main
    secrets: inherit

  quality-gate:
    if: always()
    permissions: {}
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check results
        run: |
          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "build failed"
            exit 1
          fi
